name: postman
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  iconsax_flutter: ^1.0.1
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^19.2.1
  internet_connection_checker_plus: ^2.7.2
  fpdart: ^1.1.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  get_it: ^8.0.3
  flutter_native_splash: ^2.4.6
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.2.0
  json_annotation: ^4.9.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.3
  custom_lint: ^0.7.5
  riverpod_generator: ^2.6.5
  flutter_lints: ^5.0.0
  objectbox_generator: ^4.2.0
  freezed: ^3.1.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/pfp/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
